// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwpuzywusqlmknkrwkkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3cHV6eXd1c3FsbWtua3J3a2tnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTgwMTUsImV4cCI6MjA2NDU3NDAxNX0.aGaI9d-4IvBKn_3dmQruryGZOL_is7gAIzozd5zzu4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);